const activeWardens = [
  {
    name: "Dr. Babul Prasad Tewari",
    email: "bptewari.cse@nitdgp.ac.in",
    phone: "6297479700",
    hallNumber: 1,
    profilePhoto: "https://nitdgp.ac.in/uploads/ratnesh.jpg",
  },
  {
    name: "Dr. Ratnesh Kumar",
    email: "rkumar.me@nitdgp.ac.in",
    phone: "9434789068",
    hallNumber: 1,
    profilePhoto: "https://nitdgp.ac.in/uploads/parag1.jpg",
  },
  {
    name: "Dr. Parag Kumar Guhathakurta",
    email: "pkguhathakurta.cse@nitdgp.ac.in",
    phone: "9434788159",
    hallNumber: 2,
    profilePhoto: "https://nitdgp.ac.in/uploads/s_batyabal.jpg",
  },
  {
    name: "Dr. Suvadip Batabyal",
    email: "sbatabyal.cse@nitdgp.ac.in",
    phone: "9477484204",
    hallNumber: 2,
    profilePhoto: "https://nitdgp.ac.in/uploads/soumya1.jpg",
  },
  {
    name: "Dr. Soumya Chatterjee",
    email: "schatterjee.ee@nitdgp.ac.in",
    phone: "9051016652",
    hallNumber: 3,
    profilePhoto: "https://nitdgp.ac.in/uploads/Sukhendra_Singh_Photo1.jpg",
  },
  {
    name: "Dr. Sukhendra Singh",
    email: "ssingh.bt@nitdgp.ac.in",
    phone: null,
    hallNumber: 3,
    profilePhoto: "https://nitdgp.ac.in/uploads/kiran1.jpg",
  },
  {
    name: "Dr. Rajdip Dey",
    email: "rdey.ee@nitdgp.ac.in",
    phone: "9434789026",
    hallNumber: 9,
    profilePhoto: "https://nitdgp.ac.in/uploads/santanu.jpg",
  },
  {
    name: "Dr. Santanu Paul",
    email: "spaul.ee@nitdgp.ac.in",
    phone: null,
    hallNumber: 9,
    profilePhoto: "https://nitdgp.ac.in/uploads/Krishna_Priya_Yagati1.png",
  },
  {
    name: "Dr. Surajit Biswas",
    email: "sbiswas.maths@nitdgp.ac.in",
    phone: null,
    hallNumber: 11,
    profilePhoto: "https://nitdgp.ac.in/uploads/ankush.jpeg",
  },
  {
    name: "Dr. Ankush Acharyya",
    email: "aacharyya.cse@nitdgp.ac.in",
    phone: null,
    hallNumber: 11,
    profilePhoto: "https://nitdgp.ac.in/uploads/SANDEEP_IMAGE1.jpg",
  },
  {
    name: "Dr. Sandeep Kumar",
    email: "skumar.me@nitdgp.ac.in",
    phone: "9679828237",
    hallNumber: 11,
    profilePhoto: "https://nitdgp.ac.in/uploads/Jayabrata_Dhar.jpg",
  },
  {
    name: "Dr. Jayabrata Dhar",
    email: "jdhar.me@nitdgp.ac.in",
    phone: "9434789082",
    hallNumber: 11,
    profilePhoto: "https://nitdgp.ac.in/uploads/SR_Photo1.jpeg",
  },
  {
    name: "Dr. Asmita Bose",
    email: "abose.ee@nitdgp.ac.in",
    phone: "7430033888",
    hallNumber: 13,
    profilePhoto: "https://nitdgp.ac.in/uploads/5c8d261f9277a94dde762e0fdf2a8d8f1.jpg",
  },
  {
    name: "Dr. Manisha Bal",
    email: "mbal.che@nitdgp.ac.in",
    phone: "8617469078",
    hallNumber: 13,
    profilePhoto: "https://nitdgp.ac.in/uploads/d3070927be73209252ded1e2f7fe8ee81.jpg",
  },
  {
    name: "Dr. Rajashree Das",
    email: "rdas.ece@nitdgp.ac.in",
    phone: "9434789080",
    hallNumber: 13,
    profilePhoto: "https://nitdgp.ac.in/uploads/5e29e5a38e026ed6c1ac983bdd682e4e1.jpg",
  },
  {
    name: "Dr. Karthikeyan Jeyakumar",
    email: "kjeyakumar.phy@nitdgp.ac.in",
    phone: "9434789059",
    hallNumber: 14,
    profilePhoto: "https://nitdgp.ac.in/uploads/68514ebf8a7446ae6df7c8b046998f641.jpeg",
  },
  {
    name: "Dr. Ashutosh Roushan",
    email: "aroushan.me@nitdgp.ac.in",
    phone: "6392683621",
    hallNumber: 14,
    profilePhoto: "https://nitdgp.ac.in/uploads/Dr__Ajit_11401.jpeg",
  },
  {
    name: "Dr. Ajit Kumar",
    email: "akumar.ece@nitdgp.ac.in",
    phone: "8340717097",
    hallNumber: 14,
    profilePhoto: "https://nitdgp.ac.in/uploads/Alam_Photo1.jpg",
  },
  {
    name: "Dr. Md. Sarfaraj Alam Ansari",
    email: "msaansari.cse@nitdgp.ac.in",
    phone: "9332342995",
    hallNumber: 14,
    profilePhoto: "https://nitdgp.ac.in/uploads/Mukesh_Photo1.jpg",
  },
  {
    name: "Dr. Mukesh Kumar",
    email: "mkumar.me@nitdgp.ac.in",
    phone: "8011990724",
    hallNumber: 14,
    profilePhoto: null,
  },
];

export default activeWardens;
