const wardens = [
  // Hall 1
  {
    name: "Dr. Irfan Ahmed",
    username: "warden1a",
    password: "warden1",
    role: "warden",
    designation: "Warden",
    officePhone: "9975933103",
    email: "airfan.ee@nitdgp.ac.in",
    hallNumber: 1,
  },
  {
    name: "Dr. Subhas Chandra Sahana",
    username: "warden1b",
    password: "warden1",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9402135453",
    email: "scsahana.cse@nitdgp.ac.in",
    hallNumber: 1,
  },

  // Hall 2
  {
    name: "Dr. Parag Kumar Guhathakurta",
    username: "warden2a",
    password: "warden2",
    role: "warden",
    designation: "Warden",
    officePhone: "9434788159",
    email: "pkguhathakurta.cse@nitdgp.ac.in",
    hallNumber: 2,
  },
  {
    name: "Dr. Suvadip Batabyal",
    username: "warden2b",
    password: "warden2",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9477484204",
    email: "sbatabyal.cse@nitdgp.ac.in",
    hallNumber: 2,
  },

  // Hall 3
  {
    name: "Dr. Rajib Ghosh Chaudhuri",
    username: "warden3a",
    password: "warden3",
    role: "warden",
    designation: "Warden",
    officePhone: "7596854649",
    email: "rgchaudhuri.che@nitdgp.ac.in",
    hallNumber: 3,
  },
  {
    name: "Dr. Tushar Kanti Bera",
    username: "warden3b",
    password: "warden3",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9448853308",
    email: "tkbera.ee@nitdgp.ac.in",
    hallNumber: 3,
  },

  // Hall 4
  {
    name: "Dr. Arghya Chatterjee",
    username: "warden4a",
    password: "warden4",
    role: "warden",
    designation: "Warden",
    officePhone: "9434789060",
    email: "achatterjee.phy@nitdgp.ac.in",
    hallNumber: 4,
  },
  {
    name: "Dr. Sudipta Mondal",
    username: "warden4b",
    password: "warden4",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9434789057",
    email: "smondal.bt@nitdgp.ac.in",
    hallNumber: 4,
  },

  // Hall 5
  {
    name: "Dr. Biman Kumar Saha Roy",
    username: "warden5a",
    password: "warden5",
    role: "warden",
    designation: "Warden",
    officePhone: "9434789043",
    email: "bksroy.ee@nitdgp.ac.in",
    hallNumber: 5,
  },
  {
    name: "Dr. Debayan Das",
    username: "warden5b",
    password: "warden5",
    role: "warden",
    designation: "Associate Warden",
    officePhone: null,
    email: "ddas.che@nitdgp.ac.in",
    hallNumber: 5,
  },

  // Hall 6
  {
    name: "Dr. Deepanwita Das",
    username: "warden6",
    password: "warden6",
    role: "warden",
    designation: "Warden",
    officePhone: "9434788179",
    email: "ddas.cse@nitdgp.ac.in",
    hallNumber: 6,
  },

  // Hall 7
  {
    name: "Dr. Sayantari Ghosh",
    username: "warden7a",
    password: "warden7",
    role: "warden",
    designation: "Warden",
    officePhone: "9434789054",
    email: "sghosh.phy@nitdgp.ac.in",
    hallNumber: 7,
  },
  {
    name: "Dr. Shyantani Maiti",
    username: "warden7b",
    password: "warden7",
    role: "warden",
    designation: "Associate Warden",
    officePhone: null,
    email: "smaiti.cse@nitdgp.ac.in",
    hallNumber: 7,
  },

  // Hall 8
  {
    name: "Dr. Monalisa Mandal",
    username: "warden8a",
    password: "warden8",
    role: "warden",
    designation: "Warden",
    officePhone: "9337112670",
    email: "mmandal.cse@nitdgp.ac.in",
    hallNumber: 8,
  },
  {
    name: "Dr. Sutanuka Banerjee",
    username: "warden8b",
    password: "warden8",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "7908733891",
    email: "sbanerjee.hu@nitdgp.ac.in",
    hallNumber: 8,
  },

  // Hall 9
  {
    name: "Dr. Nilanjan Biswas",
    username: "warden9a",
    password: "warden9",
    role: "warden",
    designation: "Warden",
    officePhone: null,
    email: "nbiswas.ece@nitdgp.ac.in",
    hallNumber: 9,
  },
  {
    name: "Dr. Rajdip Dey",
    username: "warden9b",
    password: "warden9",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9434789026",
    email: "rdey.ee@nitdgp.ac.in",
    hallNumber: 9,
  },

  // Hall 10
  {
    name: "Dr. Krishna Priya Yagati",
    username: "warden10",
    password: "warden10",
    role: "warden",
    designation: "Warden",
    officePhone: "9434789041",
    email: "kpyagati.mme@nitdgp.ac.in",
    hallNumber: 10,
  },

  // Hall 11
  {
    name: "Dr. Ankush Acharyya",
    username: "warden11a",
    password: "warden11",
    role: "warden",
    designation: "Warden",
    officePhone: null,
    email: "aacharyya.cse@nitdgp.ac.in",
    hallNumber: 11,
  },
  {
    name: "Dr. Arjyajyoti Goswami",
    username: "warden11b",
    password: "warden11",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9953167384",
    email: "agoswami.me@nitdgp.ac.in",
    hallNumber: 11,
  },
  {
    name: "Dr. Jayabrata Dhar",
    username: "warden11c",
    password: "warden11",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9434789082",
    email: "jdhar.me@nitdgp.ac.in",
    hallNumber: 11,
  },

  // Hall 12
  {
    name: "Dr. Narayan Murmu",
    username: "warden12a",
    password: "warden12",
    role: "warden",
    designation: "Warden",
    officePhone: "9434788096",
    email: "nmurmu.cse@nitdgp.ac.in",
    hallNumber: 12,
  },
  {
    name: "Dr. Sushovan Dutta",
    username: "warden12b",
    password: "warden12",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9434789065",
    email: "sdutta.ce@nitdgp.ac.in",
    hallNumber: 12,
  },

  // Hall 13
  {
    name: "Dr. Manisha Bal",
    username: "warden13a",
    password: "warden13",
    role: "warden",
    designation: "Warden",
    officePhone: "8617469078",
    email: "mbal.che@nitdgp.ac.in",
    hallNumber: 13,
  },
  {
    name: "Dr. Rajashree Das",
    username: "warden13b",
    password: "warden13",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9434789080",
    email: "rdas.ece@nitdgp.ac.in",
    hallNumber: 13,
  },

  // Hall 14
  {
    name: "Dr. Aritro Dey",
    username: "warden14a",
    password: "warden14",
    role: "warden",
    designation: "Warden",
    officePhone: "8971597360",
    email: "adey.ee@nitdgp.ac.in",
    hallNumber: 14,
  },
  {
    name: "Dr. Deb Ranjan Banerjee",
    username: "warden14b",
    password: "warden14",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9434788017",
    email: "drbanerjee.ch@nitdgp.ac.in",
    hallNumber: 14,
  },
  {
    name: "Dr. Md Firoz Ali",
    username: "warden14c",
    password: "warden14",
    role: "warden",
    designation: "Associate Warden",
    officePhone: "9434789045",
    email: "fali.maths@nitdgp.ac.in",
    hallNumber: 14,
  },
];

export default wardens;